apiVersion: v1
kind: Service
metadata:
  name: myway-backend
  namespace: myway
  labels:
    app: myway-backend
    component: backend
    project: myway
  annotations:
    description: "Myway Backend API Service"
spec:
  type: NodePort
  selector:
    app: myway-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30500
      protocol: TCP
  sessionAffinity: None
